version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev"
    labels:
      - "github actions"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    target-branch: "dev"
    labels:
      - "dependencies"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
