version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev"
    labels:
      - "github actions"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    versioning-strategy: lockfile-only
    directory: /
    target-branch: "dev"
    labels:
      - "dependencies"
    schedule:
      interval: weekly
