default: true
no-hard-tabs: true
MD007:
  indent: 4
MD013:
  line_length: 88
MD033:
  allowed_elements:
    - "br"
    - "table"
    - "tr"
    - "th"
    - "td"
    - "img"
    - "sup"
    - "sub"
MD041: false
