site_name: Lmo
site_description: Robust stats and fitting using (trimmed) L-Moments
site_author: Joren Hammudoglu
site_url: https://jorenham.github.io/Lmo/

repo_name: jorenham/Lmo
repo_url: https://github.com/jorenham/Lmo/

strict: true

nav:
  - Overview: index.md
  - Distributions: distributions.md
  - API Reference: api.md
  - Contributing: contributing.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    # - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    scheme: slate
    primary: nose
    accent: skin
  font:
    text: Fira Sans
    code: Fira Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jorenham/

plugins:
  - include-markdown
  - autorefs
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - url: https://docs.python.org/3/objects.inv
            - url: https://numpy.org/doc/stable/objects.inv
            - url: https://docs.scipy.org/doc/scipy/objects.inv
            - url: https://pandas.pydata.org/docs/objects.inv
          options:
            annotations_path: source
            docstring_section_style: spacy
            line_length: 79
            load_external_modules: true
            members_order: source
            merge_init_into_class: true
            show_bases: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_root_toc_entry: false
            show_source: false
            show_submodules: false
            signature_crossrefs: true
  - git-revision-date-localized:
      type: iso_date

markdown_extensions:
  # https://python-markdown.github.io/extensions/
  - admonition
  - extra
  - md_in_html
  - sane_lists
  - smarty
  - toc:
      permalink: true

  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - styles/theme.css

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs
  - lmo
