site_name: Lmo
site_description: Robust stats and fitting using (trimmed) L-Moments
site_author: Joren Hammudoglu
site_url: https://jorenham.github.io/Lmo/

repo_name: jorenham/Lmo
repo_url: https://github.com/jorenham/Lmo/

strict: true

nav:
  - Overview: index.md
  - Reference: api.md
  - Distributions: distributions.md
  - Contributing: contributing.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  features:
    - content.tabs.link
    - content.tooltips
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  font:
    text: Fira Sans
    code: Fira Mono
  palette:
    scheme: slate
    primary: nose
    accent: skin

extra:
  analytics:
    provider: google
    property: G-KH79N7XQCE
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jorenham/

plugins:
  # https://github.com/mkdocstrings/autorefs
  - autorefs

  # https://github.com/shyamd/mkdocs-bibtex
  - bibtex:
      bib_file: docs/bib/refs.bib
      bib_dir: docs/bib
      bib_by_default: false

  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      type: iso_date

  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - include-markdown

  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify:
      cache_safe: true
      minify_css: true
      minify_html: true
      minify_js: true
      js_files:
        - scripts/katex.js
      css_files:
        - styles/theme.css

  # https://github.com/mkdocstrings/mkdocstrings
  # https://github.com/mkdocstrings/python
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - url: https://docs.python.org/3/objects.inv
            - url: https://numpy.org/doc/stable/objects.inv
            - url: https://docs.scipy.org/doc/scipy/objects.inv
            - url: https://pandas.pydata.org/docs/objects.inv
          options:
            annotations_path: source
            docstring_section_style: spacy
            line_length: 79
            load_external_modules: true
            members_order: source
            merge_init_into_class: true
            show_bases: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_root_toc_entry: false
            show_source: false
            show_submodules: false
            signature_crossrefs: true

  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search

markdown_extensions:
  # https://python-markdown.github.io/extensions/
  - abbr
  - attr_list
  - def_list
  - extra
  - footnotes
  - md_in_html
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true

  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
  - styles/theme.css
  - styles/katex.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/copy-tex.min.js
  - scripts/katex.js

watch:
  - docs
  - lmo
