name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.12']
        pandas: ['without', 'with']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: poetry check
        run: poetry check

      - name: poetry install
        run: >
          poetry install
          --sync
          --with github
          --without docs
          --without debug
          --${{ matrix.pandas }} pandas

      - name: codespell
        run: poetry run codespell .

      - name: ruff check
        run: poetry run ruff check --output-format=github .

      - name: pyright
        run: poetry run pyright >> $GITHUB_STEP_SUMMARY

      - name: pytest
        run: poetry run pytest
